/* Generated by AN DISI Unibo */ 
package it.unibo.monitoring_device

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024
import main.resources.LedFactory

class Monitoring_device ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val led = LedFactory.create("isico","localhost","8021")
		var statusInc = "off"
			  var statusAsh = "empty" 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						delay(150) 
						observeResource("localhost","8021","ctxashstorage","datacleaner","info")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="update",cond=whenDispatch("info"))
					transition(edgeName="t01",targetState="handleStartBurn",cond=whenEvent("startBurn"))
					transition(edgeName="t02",targetState="handleEndBurn",cond=whenEvent("endBurn"))
				}	 
				state("update") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("info(SOURCE,VAL,VAR)"), Term.createTerm("info(SOURCE,VAL,VAR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val SOURCE = payloadArg(0)   
								 val VAR = payloadArg(1) 
								 val VAL = payloadArg(2) 
								
													if(VAR.equals("ashLevel")&&VAL.equals("full")){
														statusAsh = "full"
														led.turnBlink();
													}
													if(VAR.equals("ashLevel")&&VAL.equals("empty")){
														statusAsh = "empty"	
														led.turnBlink();
													}
													if(VAR.equals("ashLevel")&&VAL.equals("half")){
														statusAsh= "half";
													}
								emit("sonarUpdate", "sonarUpdate($VAR)" ) 
								
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="update",cond=whenDispatch("info"))
				}	 
				state("handleStartBurn") { //this:State
					action { //it:State
						
									led.turnOn();
									statusInc = "on"
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t14",targetState="update",cond=whenDispatch("info"))
					transition(edgeName="t15",targetState="handleEndBurn",cond=whenEvent("endBurn"))
				}	 
				state("handleEndBurn") { //this:State
					action { //it:State
						
									led.turnOff();
									statusInc = "off"
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t16",targetState="update",cond=whenDispatch("info"))
					transition(edgeName="t17",targetState="handleStartBurn",cond=whenEvent("startBurn"))
				}	 
			}
		}
} 
