/* Generated by AN DISI Unibo */ 
package it.unibo.ctx2
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "localhost", this, "ctx2.pl", "sysRules.pl", "ctx2"
	)
	//JAN Facade
	//JAN24 Display
}

