/* Generated by AN DISI Unibo */ 
package it.unibo.test_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Test_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var N = ""; var VAL = ""; var VAR = ""  ; var RobotFree = "";var As_status="" ; var Ws_status="" 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						delay(500) 
						observeResource("localhost","6969","ctxtest","wis","info")
						forward("robotUpdate", "robotUpdate(RobotFree)" ,"wis" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="s1",cond=whenDispatch("info"))
				}	 
				state("s1") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("info(N,VAR,VAL)"), Term.createTerm("info(N,VAL,VAR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 N = payloadArg(0)  
								 VAR = payloadArg(1) 
								 VAL = payloadArg(2) 
								CommUtils.outmagenta("$name views $N $VAR $VAL")
								if(VAR.equals("RobotFree")){
								    				RobotFree=VAL;
								    			} else if(VAR.equals("As_status")){
								    				As_status=VAL;
								    			} else{
								  					Ws_status=VAL;
								    			}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="s1",cond=whenDispatch("info"))
					transition(edgeName="t14",targetState="s2",cond=whenRequest("testRequest"))
				}	 
				state("s2") { //this:State
					action { //it:State
						var RESULT = "$RobotFree,$As_status,$Ws_status" 
						CommUtils.outyellow("$name print: $RESULT")
						answer("testRequest", "testReply", "testReply($RESULT)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t15",targetState="s1",cond=whenDispatch("info"))
					transition(edgeName="t16",targetState="s2",cond=whenRequest("testRequest"))
				}	 
			}
		}
} 
