/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "initialize"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 	
			var RobotState = "IDLE";
			var MentalState = "";
			val Waste_x = 0; //waste
			val Waste_y = 4;		
			val In_x = 3; //burnin
			val In_y = 1;
			val Ho_x = 0; //home
			val Ho_y = 0;
			val Bo_x = 4; //burnout
			val Bo_y = 3;
			val Ao_x = 6; //AshOut
			val Ao_y = 4;
		return { //this:ActionBasciFsm
				state("initialize") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						delay(1000) 
						CommUtils.outmagenta("$name | $MyName engaging ... ")
						request("engage", "engage($MyName,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="home",cond=whenReply("engagedone"))
					transition(edgeName="t05",targetState="end",cond=whenReply("engagerefused"))
				}	 
				state("home") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 MentalState="HOME" 
						CommUtils.outmagenta("($name): $MentalState")
						updateResourceRep(  "info($name,MentalState,$MentalState)"  
						)
						if( checkMsgContent( Term.createTerm("engagedone(ARG)"), Term.createTerm("engagedone(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("($name): $RobotState")
								updateResourceRep(  "info($name,RobotState,$RobotState)"  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="goToWasteIn",cond=whenDispatch("robotStart"))
					transition(edgeName="t07",targetState="home_go_burnOut",cond=whenEvent("endBurn"))
				}	 
				state("goToWasteIn") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 RobotState="WORKING" 
						updateResourceRep(  "info($name,RobotState,$RobotState)"  
						)
						request("moverobot", "moverobot($Waste_x,$Waste_y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t18",targetState="loadRP",cond=whenReply("moverobotdone"))
					transition(edgeName="t19",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("loadRP") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 MentalState="WASTEIN" 
						updateResourceRep(  "info($name,MentalState,$MentalState)"  
						)
						request("moverobot", "moverobot($In_x,$In_y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t210",targetState="startBurn",cond=whenReply("moverobotdone"))
					transition(edgeName="t211",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("startBurn") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 MentalState="BURNIN" 
						updateResourceRep(  "info($name,MentalState,$MentalState)"  
						)
						delay(5000) 
						emit("startBurn", "startBurn(1)" ) 
						request("moverobot", "moverobot($Ho_x,$Ho_y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t312",targetState="home",cond=whenReply("moverobotdone"))
					transition(edgeName="t313",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("home_go_burnOut") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						request("moverobot", "moverobot($Bo_x,$Bo_y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t414",targetState="gatheringAsh",cond=whenReply("moverobotdone"))
					transition(edgeName="t415",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("gatheringAsh") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 MentalState="BURNOUT" 
						updateResourceRep(  "info($name,MentalState,$MentalState)"  
						)
						delay(1000) 
						request("moverobot", "moverobot($Ao_x,$Ao_y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t516",targetState="unload",cond=whenReply("moverobotdone"))
					transition(edgeName="t517",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("unload") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 MentalState="ASHOUT" 
						 RobotState="IDLE" 
						updateResourceRep(  "info($name,RobotState,$RobotState)"  
						)
						updateResourceRep(  "info($name,MentalState,$MentalState)"  
						)
						request("moverobot", "moverobot($Ho_x,$Ho_y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t618",targetState="home",cond=whenReply("moverobotdone"))
					transition(edgeName="t619",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("end") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						System.exit(-1) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
